<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260528083116 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE etf (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, isin VARCHAR(12) NOT NULL, symbol VARCHAR(32) NOT NULL, name VARCHAR(128) NOT NULL, exchange VARCHAR(32) NOT NULL, currency VARCHAR(8) NOT NULL, pea_eligible BOOLEAN NOT NULL, active BOOLEAN NOT NULL, bourso_identifier VARCHAR(64) DEFAULT NULL, data_provider_symbol VARCHAR(64) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_etf_isin ON etf (isin)');
        $this->addSql('CREATE UNIQUE INDEX uniq_etf_symbol_exchange ON etf (symbol, exchange)');
        $this->addSql('CREATE TABLE momentum_snapshot (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, computed_at DATE NOT NULL, strategy_code VARCHAR(64) NOT NULL, score NUMERIC(10, 4) NOT NULL, performance_1_month NUMERIC(10, 4) DEFAULT NULL, performance_3_months NUMERIC(10, 4) DEFAULT NULL, performance_6_months NUMERIC(10, 4) DEFAULT NULL, performance_12_months NUMERIC(10, 4) DEFAULT NULL, volatility_annualized NUMERIC(10, 4) DEFAULT NULL, max_drawdown NUMERIC(10, 4) DEFAULT NULL, moving_average_50 NUMERIC(18, 6) DEFAULT NULL, moving_average_200 NUMERIC(18, 6) DEFAULT NULL, distance_to_moving_average_200 NUMERIC(10, 4) DEFAULT NULL, atr_14 NUMERIC(10, 4) DEFAULT NULL, signal VARCHAR(16) NOT NULL, details JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, etf_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_35E0605862E4CDB8 ON momentum_snapshot (etf_id)');
        $this->addSql('CREATE INDEX idx_momentum_snapshot_strategy_score ON momentum_snapshot (strategy_code, score)');
        $this->addSql('CREATE UNIQUE INDEX uniq_momentum_snapshot_etf_date_strategy ON momentum_snapshot (etf_id, computed_at, strategy_code)');
        $this->addSql('CREATE TABLE price_point (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, priced_at DATE NOT NULL, open_price NUMERIC(18, 6) DEFAULT NULL, high_price NUMERIC(18, 6) DEFAULT NULL, low_price NUMERIC(18, 6) DEFAULT NULL, close_price NUMERIC(18, 6) NOT NULL, adjusted_close_price NUMERIC(18, 6) DEFAULT NULL, volume INT DEFAULT NULL, source VARCHAR(32) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, etf_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9C6CFB4462E4CDB8 ON price_point (etf_id)');
        $this->addSql('CREATE INDEX idx_price_point_etf_date ON price_point (etf_id, priced_at)');
        $this->addSql('CREATE UNIQUE INDEX uniq_price_point_etf_date_source ON price_point (etf_id, priced_at, source)');
        $this->addSql('ALTER TABLE momentum_snapshot ADD CONSTRAINT FK_35E0605862E4CDB8 FOREIGN KEY (etf_id) REFERENCES etf (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE price_point ADD CONSTRAINT FK_9C6CFB4462E4CDB8 FOREIGN KEY (etf_id) REFERENCES etf (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE momentum_snapshot DROP CONSTRAINT FK_35E0605862E4CDB8');
        $this->addSql('ALTER TABLE price_point DROP CONSTRAINT FK_9C6CFB4462E4CDB8');
        $this->addSql('DROP TABLE etf');
        $this->addSql('DROP TABLE momentum_snapshot');
        $this->addSql('DROP TABLE price_point');
    }
}
